name: trabajomovilesg5
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2

  equatable: ^2.0.5
  get_it: ^7.6.0
  intl: ^0.18.1
  floor: ^1.4.2
  retrofit: ^3.0.1
  flutter_hooks: ^0.18.3
  cached_network_image: ^3.2.0

  # path
  file_picker: ^6.1.1
  path: ^1.8.3
  path_provider: ^2.1.1

  open_filex: ^4.3.2
  pdf: ^3.10.4
  fluttertoast: ^8.2.2
  google_fonts: ^6.1.0
  http: any

  # display pdf
  flutter_pdfview: ^1.3.2

  #Dependencias de firebase
  firebase_core: ^2.8.0
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: 3.0.1+1
  floor_generator: 1.2.0
  build_runner: 2.1.2

flutter:

  uses-material-design: true

  assets:
    - assets/SPI-FISI_logo.jpg
    - assets/foto_de_perfil.jpg
    - assets/pdf_icon.jpg
    - assets/UNMSM-logo.png
    - assets/unmsmlogo.png
    - assets/formulario1.jpg
    - assets/MD2.pdf
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
