// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgG6eCXaReDlrh1KIULMMzQCwphzTlVZ0',
    appId: '1:365345439477:web:2458a2c1a9c24ab8b40fbc',
    messagingSenderId: '365345439477',
    projectId: 'proyecto-moviles-g5',
    authDomain: 'proyecto-moviles-g5.firebaseapp.com',
    storageBucket: 'proyecto-moviles-g5.appspot.com',
    measurementId: 'G-E80BMYJYC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg54eDSYFUB4Yds_WjMIm1ttAlFtIoKKY',
    appId: '1:365345439477:android:2e260f52ec463801b40fbc',
    messagingSenderId: '365345439477',
    projectId: 'proyecto-moviles-g5',
    storageBucket: 'proyecto-moviles-g5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXKx6vXIL_-d47DricurpvlauaaJxi66w',
    appId: '1:365345439477:ios:2cbf3e0701692039b40fbc',
    messagingSenderId: '365345439477',
    projectId: 'proyecto-moviles-g5',
    storageBucket: 'proyecto-moviles-g5.appspot.com',
    iosBundleId: 'com.example.trabajomovilesg5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXKx6vXIL_-d47DricurpvlauaaJxi66w',
    appId: '1:365345439477:ios:2647270d1299342cb40fbc',
    messagingSenderId: '365345439477',
    projectId: 'proyecto-moviles-g5',
    storageBucket: 'proyecto-moviles-g5.appspot.com',
    iosBundleId: 'com.example.trabajomovilesg5.RunnerTests',
  );
}
